# Generated by Django 5.2.12 on 2026-03-23 03:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_code', models.IntegerField()),
                ('source_job_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('inputs_json', models.TextField(default='[]')),
                ('timeout_sec', models.IntegerField(default=1800)),
                ('status', models.CharField(choices=[('queued', 'Na fila'), ('running', 'Executando'), ('scheduled', 'Agendado'), ('finished', 'Concluído'), ('error', 'Erro'), ('cancelled', 'Cancelado')], default='queued', max_length=24)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('agent', models.CharField(blank=True, default='', max_length=128)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(help_text='Lobby account (always set)', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.account')),
                ('game_account', models.ForeignKey(blank=True, help_text='Game account (set for per-server jobs like check_status)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.gameaccount')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.node')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('debug', 'Debug'), ('warn', 'Aviso'), ('error', 'Erro')], default='info', max_length=16)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='jobs.job')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['account', 'status'], name='jobs_job_account_aede7f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['action_code'], name='jobs_job_action__a157ef_idx'),
        ),
    ]
