# Generated by Django 5.2.12 on 2026-03-31 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_session_cache_to_gameaccount'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='inputs_json',
            field=models.TextField(default='{}'),
        ),
        migrations.CreateModel(
            name='ConstructionResourceReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.CharField(max_length=64)),
                ('city_name', models.CharField(blank=True, default='', max_length=120)),
                ('resource', models.CharField(max_length=24)),
                ('reserved_local_amount', models.BigIntegerField(default=0)),
                ('shortfall_amount', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('released', 'Liberada'), ('spent', 'Consumida'), ('cancelled', 'Cancelada')], default='active', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_reservations', to='accounts.account')),
                ('game_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_reservations', to='accounts.gameaccount')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_reservations', to='jobs.job')),
            ],
            options={
                'ordering': ['city_name', 'resource'],
                'indexes': [models.Index(fields=['game_account', 'status'], name='jobs_constr_game_ac_ea1bc6_idx'), models.Index(fields=['job', 'status'], name='jobs_constr_job_id_14520f_idx'), models.Index(fields=['city_id', 'resource'], name='jobs_constr_city_id_fc7f44_idx')],
            },
        ),
    ]
