# Generated by Codex on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job_root_job_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["-created_at"], name="jobs_job_created_1c7e88_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["status", "-created_at"], name="jobs_job_status_1d696a_idx"),
        ),
    ]
