# Generated by Codex on 2026-04-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0006_add_market_limits_to_gameaccount"),
        ("profiles", "0001_initial"),
        ("jobs", "0005_job_created_at_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("workflow_type", models.CharField(db_index=True, max_length=64)),
                ("category", models.CharField(blank=True, db_index=True, default="", max_length=32)),
                ("scope_json", models.TextField(default="{}")),
                ("config_json", models.TextField(default="{}")),
                ("status", models.CharField(choices=[("draft", "Rascunho"), ("active", "Ativo"), ("paused", "Pausado"), ("waiting", "Aguardando"), ("problem", "Com problema"), ("finished", "Concluido"), ("cancelled", "Cancelado")], db_index=True, default="draft", max_length=24)),
                ("next_scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_summary", models.TextField(blank=True, default="")),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workflows", to="accounts.account")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_workflows", to=settings.AUTH_USER_MODEL)),
                ("game_account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="workflows", to="accounts.gameaccount")),
                ("node", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workflows", to="accounts.node")),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("trigger_type", models.CharField(blank=True, default="manual", max_length=32)),
                ("status", models.CharField(choices=[("scheduled", "Agendado"), ("running", "Executando"), ("waiting", "Aguardando"), ("problem", "Com problema"), ("finished", "Concluido"), ("cancelled", "Cancelado")], db_index=True, default="scheduled", max_length=24)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("summary_json", models.TextField(default="{}")),
                ("stats_json", models.TextField(default="{}")),
                ("error_summary", models.TextField(blank=True, default="")),
                ("workflow", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="jobs.workflow")),
            ],
            options={
                "ordering": ["-sequence", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="workflow",
            name="active_run",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="active_for_workflows", to="jobs.workflowrun"),
        ),
        migrations.AddField(
            model_name="job",
            name="workflow",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="jobs", to="jobs.workflow"),
        ),
        migrations.AddField(
            model_name="job",
            name="workflow_run",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="jobs", to="jobs.workflowrun"),
        ),
        migrations.AddConstraint(
            model_name="workflowrun",
            constraint=models.UniqueConstraint(fields=("workflow", "sequence"), name="jobs_workflowrun_sequence_uniq"),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(fields=["status", "-updated_at"], name="jobs_workfl_status_782fbe_idx"),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(fields=["workflow_type", "status"], name="jobs_workfl_workflo_7e8cd9_idx"),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(fields=["account", "status"], name="jobs_workfl_account_f8b9a6_idx"),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(fields=["game_account", "status"], name="jobs_workfl_game_ac_20ff93_idx"),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(fields=["node", "status"], name="jobs_workfl_node_id_08326d_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowrun",
            index=models.Index(fields=["workflow", "-sequence"], name="jobs_workfl_workflo_a34815_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowrun",
            index=models.Index(fields=["status", "-created_at"], name="jobs_workfl_status_2915e5_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["workflow", "status"], name="jobs_job_workflo_c86484_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["workflow_run", "status"], name="jobs_job_workflo_9f31b5_idx"),
        ),
    ]
