# Generated by Django 5.2.14 on 2026-05-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_workflowrun_archived_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_lease_e_be8a89_idx',
            old_name='jobs_job_lease_ex_35be31_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_created_77460a_idx',
            old_name='jobs_job_created_1c7e88_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_status_57b86b_idx',
            old_name='jobs_job_status_1d696a_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_workflo_fd53d4_idx',
            old_name='jobs_job_workflo_c86484_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_workflo_a76031_idx',
            old_name='jobs_job_workflo_9f31b5_idx',
        ),
        migrations.RenameIndex(
            model_name='workflow',
            new_name='jobs_workfl_status_bce1b0_idx',
            old_name='jobs_workfl_status_782fbe_idx',
        ),
        migrations.RenameIndex(
            model_name='workflow',
            new_name='jobs_workfl_workflo_6eeb86_idx',
            old_name='jobs_workfl_workflo_7e8cd9_idx',
        ),
        migrations.RenameIndex(
            model_name='workflow',
            new_name='jobs_workfl_account_3a8b02_idx',
            old_name='jobs_workfl_account_f8b9a6_idx',
        ),
        migrations.RenameIndex(
            model_name='workflow',
            new_name='jobs_workfl_game_ac_9d00ec_idx',
            old_name='jobs_workfl_game_ac_20ff93_idx',
        ),
        migrations.RenameIndex(
            model_name='workflow',
            new_name='jobs_workfl_node_id_c03625_idx',
            old_name='jobs_workfl_node_id_08326d_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowrun',
            new_name='jobs_workfl_workflo_fb4bfc_idx',
            old_name='jobs_workfl_workflo_a34815_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowrun',
            new_name='jobs_workfl_status_4fa6eb_idx',
            old_name='jobs_workfl_status_2915e5_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('queued', 'Na fila'), ('running', 'Executando'), ('scheduled', 'Agendado'), ('finished', 'Concluido'), ('error', 'Erro'), ('cancelled', 'Cancelado')], default='queued', max_length=24),
        ),
    ]
