# Generated by Django 5.2.14 on 2026-05-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_add_job_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
