# Generated by Django 5.2.12 on 2026-03-23 03:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=96, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('action_code', models.IntegerField()),
                ('inputs_json', models.TextField(default='[]', help_text='JSON array of default input values')),
                ('timeout_sec', models.IntegerField(default=1800)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
