# Generated by Django 5.2.12 on 2026-03-23 03:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalMarketOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_city_index', models.IntegerField(default=1)),
                ('buyer_market_city_index', models.IntegerField(blank=True, null=True)),
                ('seller_city_index', models.IntegerField(blank=True, null=True)),
                ('resource_idx', models.IntegerField(choices=[(0, 'Madeira'), (1, 'Vinho'), (2, 'Mármore'), (3, 'Cristal'), (4, 'Enxofre')])),
                ('amount', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=12)),
                ('status', models.CharField(choices=[('created', 'Criado'), ('matched', 'Pareado'), ('jobs_created', 'Jobs criados'), ('jobs_running', 'Jobs executando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('canceled', 'Cancelado')], default='created', max_length=32)),
                ('source_action_code', models.IntegerField(blank=True, null=True)),
                ('source_reason', models.CharField(blank=True, default='', max_length=128)),
                ('reason_detail', models.TextField(blank=True, default='')),
                ('production_eta_seconds', models.IntegerField(blank=True, null=True)),
                ('missing_resource_keys', models.CharField(blank=True, default='', max_length=128)),
                ('result_note', models.TextField(blank=True, default='')),
                ('buy_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.job')),
                ('buyer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_orders_as_buyer', to='accounts.account')),
                ('buyer_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_orders_buyer_node', to='accounts.node')),
                ('redistribution_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.job')),
                ('sell_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.job')),
                ('seller_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_orders_as_seller', to='accounts.account')),
                ('seller_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_orders_seller_node', to='accounts.node')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
