# Generated by Django 5.2.14 on 2026-05-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_blackmarketoffer_game_offer_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blackmarketoffer',
            new_name='market_blac_game_ac_0b1e05_idx',
            old_name='bmo_ga_status_idx',
        ),
        migrations.RenameIndex(
            model_name='blackmarketoffer',
            new_name='market_blac_unit_id_4e5d5e_idx',
            old_name='bmo_unit_status_idx',
        ),
        migrations.RenameIndex(
            model_name='blackmarketoffer',
            new_name='market_blac_game_ac_e2d0d4_idx',
            old_name='bmo_ga_city_unit_idx',
        ),
        migrations.RenameIndex(
            model_name='blackmarketunitquote',
            new_name='market_blac_game_ac_6187b0_idx',
            old_name='market_blac_game_ac_97d7ce_idx',
        ),
        migrations.RenameIndex(
            model_name='blackmarketunitquote',
            new_name='market_blac_unit_id_0d9c8f_idx',
            old_name='market_blac_unit_id_82a879_idx',
        ),
        migrations.RenameIndex(
            model_name='constructionmarketintervention',
            new_name='market_cons_game_ac_6b3394_idx',
            old_name='market_cons_game_ac_7e26ca_idx',
        ),
        migrations.RenameIndex(
            model_name='constructionmarketintervention',
            new_name='market_cons_source__30c5ce_idx',
            old_name='market_cons_source__583dff_idx',
        ),
        migrations.AlterField(
            model_name='internalmarketorder',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
    ]
