# Generated by Django 5.2.14 on 2026-05-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_blackmarketavailableoffer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blackmarketavailableoffer',
            new_name='market_blac_game_ac_00345a_idx',
            old_name='market_bmav_game_ac_buyc_idx',
        ),
        migrations.RenameIndex(
            model_name='blackmarketavailableoffer',
            new_name='market_blac_unit_id_1c2622_idx',
            old_name='market_bmav_unit_id_cat_idx',
        ),
    ]
