# Generated by Django 5.2.17 on 2026-10-05 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_gameaccount_user_agent'),
        ('jobs', '0014_workflow_list_indexes'),
        ('market', '0011_rename_market_bmav_game_ac_buyc_idx_market_blac_game_ac_00345a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicMarketScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_id', models.IntegerField()),
                ('city_name', models.CharField(blank=True, default='', max_length=128)),
                ('kind', models.CharField(choices=[('full', 'Varredura'), ('range_sync', 'So alcance')], default='full', max_length=16)),
                ('bo_level', models.IntegerField(default=0)),
                ('max_range', models.IntegerField(default=0)),
                ('range_before', models.IntegerField(default=0)),
                ('offers_count', models.IntegerField(default=0)),
                ('scanned_at', models.DateTimeField()),
                ('game_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_market_scans', to='accounts.gameaccount')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.job')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicMarketOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('sell', 'Vendendo'), ('buy', 'Comprando')], default='sell', max_length=8)),
                ('resource_idx', models.IntegerField(choices=[(0, 'Madeira'), (1, 'Vinho'), (2, 'Marmore'), (3, 'Cristal'), (4, 'Enxofre')])),
                ('city_id', models.IntegerField()),
                ('city_name', models.CharField(blank=True, default='', max_length=128)),
                ('player_name', models.CharField(blank=True, default='', max_length=128)),
                ('amount', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=0)),
                ('distance', models.IntegerField(default=0)),
                ('goods_per_minute', models.IntegerField(default=0)),
                ('is_internal', models.BooleanField(default=False)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='market.publicmarketscan')),
            ],
            options={
                'ordering': ['resource_idx', 'unit_price', 'distance'],
            },
        ),
        migrations.AddConstraint(
            model_name='publicmarketscan',
            constraint=models.UniqueConstraint(fields=('game_account', 'city_id'), name='uq_public_market_scan_ga_city'),
        ),
        migrations.AddIndex(
            model_name='publicmarketoffer',
            index=models.Index(fields=['resource_idx', 'kind', 'unit_price'], name='market_publ_resourc_ef3efe_idx'),
        ),
    ]
