# Generated by Django 5.2.12 on 2026-03-23 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webshare_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('provider', models.CharField(choices=[('webshare', 'Webshare'), ('manual', 'Manual'), ('other', 'Outro')], default='manual', help_text='Source of this proxy entry', max_length=16)),
                ('address', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(blank=True, default='', max_length=128)),
                ('password_enc', models.TextField(blank=True, default='')),
                ('country_code', models.CharField(blank=True, default='', max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.BooleanField(blank=True, help_text='True if last test succeeded, False if failed, null if never tested', null=True)),
                ('last_test_ip', models.CharField(blank=True, default='', help_text='External IP returned during last test', max_length=64)),
                ('last_test_latency_ms', models.IntegerField(blank=True, help_text='Latency in milliseconds from last test', null=True)),
                ('assigned_node', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_profile', to='accounts.node')),
            ],
            options={
                'ordering': ['address'],
            },
        ),
    ]
