# Generated by Django 5.2.12 on 2026-03-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyprofile',
            name='webshare_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
