# Generated by Django 5.2.13 on 2026-04-30 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldintel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldDumpPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(db_index=True, max_length=32)),
                ('owner_name', models.CharField(blank=True, default='', max_length=128)),
                ('ally_tag', models.CharField(blank=True, default='', max_length=32)),
                ('ally_id', models.CharField(blank=True, default='', max_length=32)),
                ('world_rank', models.PositiveIntegerField(default=0)),
                ('building_score', models.BigIntegerField(default=0)),
                ('research_score', models.BigIntegerField(default=0)),
                ('army_score', models.BigIntegerField(default=0)),
                ('trader_score', models.BigIntegerField(default=0)),
                ('city_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['world_rank'],
            },
        ),
        migrations.AddField(
            model_name='worlddumpcity',
            name='actions_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='worlddumpcity',
            name='ally_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='worlddumpcity',
            name='has_treaties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worlddumpcity',
            name='infested_by_plague',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worlddumpcity',
            name='view_able',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worlddumpisland',
            name='helios_built',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worlddumpisland',
            name='miracle_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worlddumpisland',
            name='miracle_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worlddumpisland',
            name='resource_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worlddumpisland',
            name='wood_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='worlddumpcity',
            index=models.Index(fields=['dump', 'state'], name='worldintel__dump_id_186da6_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddumpisland',
            index=models.Index(fields=['dump', 'miracle_type'], name='worldintel__dump_id_4de9ca_idx'),
        ),
        migrations.AddField(
            model_name='worlddumpplayer',
            name='dump',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='worldintel.worlddump'),
        ),
        migrations.AddIndex(
            model_name='worlddumpplayer',
            index=models.Index(fields=['dump', 'owner_id'], name='worldintel__dump_id_814718_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddumpplayer',
            index=models.Index(fields=['dump', 'ally_tag'], name='worldintel__dump_id_3e8f85_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddumpplayer',
            index=models.Index(fields=['dump', 'world_rank'], name='worldintel__dump_id_f04bed_idx'),
        ),
        migrations.AddIndex(
            model_name='worlddumpplayer',
            index=models.Index(fields=['dump', 'building_score'], name='worldintel__dump_id_1fef7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='worlddumpplayer',
            unique_together={('dump', 'owner_id')},
        ),
    ]
