# Generated by Django 5.2.13 on 2026-05-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldintel", "0004_worlddump_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="worlddumpcity",
            name="position",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
