# Generated by Django 5.2.12 on 2026-03-23 03:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('proxy', models.CharField(blank=True, default='', max_length=256)),
                ('external_ip', models.CharField(blank=True, default='', max_length=64)),
                ('ip_source', models.CharField(blank=True, default='', max_length=64)),
                ('ip_checked_at', models.DateTimeField(blank=True, null=True)),
                ('agent_name', models.CharField(blank=True, default='', max_length=128)),
                ('agent_host', models.CharField(blank=True, default='', max_length=128)),
                ('agent_image', models.CharField(blank=True, default='', max_length=255)),
                ('agent_version', models.CharField(blank=True, default='', max_length=64)),
                ('agent_last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('deploy_token', models.CharField(blank=True, default='', max_length=64)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='User-friendly name for this lobby account', max_length=64)),
                ('email', models.CharField(max_length=255)),
                ('password_enc', models.TextField(help_text='Fernet-encrypted password')),
                ('gf_token_enc', models.TextField(blank=True, default='', help_text='Fernet-encrypted gf-token-production cookie')),
                ('notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.node')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='GameAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lobby_account_id', models.IntegerField(help_text='Gameforge lobby account ID (e.g. 108637)')),
                ('server_id', models.CharField(help_text="Server identifier (e.g. 's61-br')", max_length=32)),
                ('server_language', models.CharField(help_text="Language code (e.g. 'br')", max_length=8)),
                ('server_number', models.IntegerField(help_text='Server number (e.g. 61)')),
                ('name', models.CharField(blank=True, default='', help_text="Player/character name (e.g. 'HAVIT')", max_length=128)),
                ('account_group', models.CharField(blank=True, default='', help_text="Account group identifier (e.g. 'br_61')", max_length=32)),
                ('blocked', models.BooleanField(default=False, help_text='Blocked by Gameforge (from discover_characters)')),
                ('active', models.BooleanField(default=True, help_text='User can enable/disable individual game accounts')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_accounts', to='accounts.account')),
            ],
            options={
                'ordering': ['account', 'server_id'],
                'indexes': [models.Index(fields=['lobby_account_id'], name='accounts_ga_lobby_a_18e8a9_idx'), models.Index(fields=['server_id'], name='accounts_ga_server__cafcff_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'lobby_account_id', 'server_id'), name='uq_gameaccount_lobby_server')],
            },
        ),
    ]
