# Generated by Django 5.2.12 on 2026-03-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaccount',
            name='session_cookies_enc',
            field=models.TextField(blank=True, default='', help_text='Fernet-encrypted JSON of game session cookies'),
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='session_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the cached session was last saved by the agent', null=True),
        ),
    ]
