# Generated by Django 5.2.13 on 2026-04-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_session_cache_to_gameaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaccount',
            name='build_time_reduction',
            field=models.PositiveSmallIntegerField(default=0, help_text='World build time reduction percentage (e.g. 10 for 10%). Set per server.'),
        ),
    ]
