# Generated by Django 5.2.14 on 2026-05-29 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='combatreport',
            new_name='combat_comb_game_ac_6b97a9_idx',
            old_name='combat_report_ga_date_idx',
        ),
        migrations.RenameIndex(
            model_name='combatreport',
            new_name='combat_comb_target__886345_idx',
            old_name='combat_report_target_idx',
        ),
        migrations.RenameIndex(
            model_name='combatreport',
            new_name='combat_comb_result_5603cf_idx',
            old_name='combat_report_result_idx',
        ),
    ]
