# Generated by Django 5.2.12 on 2026-03-23 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_token', models.CharField(blank=True, default='', max_length=255)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuração do Bot Telegram',
                'verbose_name_plural': 'Configuração do Bot Telegram',
            },
        ),
        migrations.CreateModel(
            name='MessageAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='telegram', max_length=32)),
                ('channel', models.CharField(default='notification', max_length=32)),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('pending', 'Pendente'), ('failed', 'Falhou'), ('retried', 'Reenviado')], default='sent', max_length=24)),
                ('agent_name', models.CharField(blank=True, default='', max_length=128)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('external_ref', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.node')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramAccountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.CharField(blank=True, default='', max_length=64)),
                ('enabled', models.BooleanField(default=False)),
                ('notify_attack_alert', models.BooleanField(default=True)),
                ('notify_job_failed', models.BooleanField(default=True)),
                ('notify_job_done', models.BooleanField(default=False)),
                ('notify_build_complete', models.BooleanField(default=False)),
                ('notify_research_complete', models.BooleanField(default=False)),
                ('notify_low_wine', models.BooleanField(default=True)),
                ('notify_daily_summary', models.BooleanField(default=False)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_config', to='accounts.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
