# Generated by Django 5.2.12 on 2026-03-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_linking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotconfig',
            name='chat_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Chat ID global'),
        ),
        migrations.AddField(
            model_name='telegrambotconfig',
            name='link_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='telegrambotconfig',
            name='link_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrambotconfig',
            name='link_status',
            field=models.CharField(choices=[('unlinked', 'Nao vinculado'), ('pending', 'Aguardando confirmacao'), ('linked', 'Vinculado')], default='unlinked', max_length=16),
        ),
        migrations.AddField(
            model_name='telegrambotconfig',
            name='notify_attack_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegrambotconfig',
            name='notify_build_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrambotconfig',
            name='notify_daily_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrambotconfig',
            name='notify_job_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrambotconfig',
            name='notify_job_failed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegrambotconfig',
            name='notify_low_wine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegrambotconfig',
            name='notify_research_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrambotconfig',
            name='telegram_username',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
