# Generated by Django 5.2.14 on 2026-05-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0010_island_monitor_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccountconfig',
            name='notify_raid_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegrambotconfig',
            name='notify_raid_alert',
            field=models.BooleanField(default=True),
        ),
    ]
