# Generated by Django 5.2.12 on 2026-03-23 03:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_snapshot', models.JSONField(blank=True, default=dict, help_text='Account-level stats (gold, research, etc.)')),
                ('cities', models.JSONField(blank=True, default=dict, help_text='Cities with resources, buildings')),
                ('military', models.JSONField(blank=True, default=dict, help_text='Troops and fleet data')),
                ('source_job_id', models.UUIDField(blank=True, null=True)),
                ('account', models.ForeignKey(help_text='Lobby account (denormalized for convenience)', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='accounts.account')),
                ('game_account', models.OneToOneField(blank=True, help_text='Game account (per-server). New snapshots should set this.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='accounts.gameaccount')),
            ],
            options={
                'verbose_name': 'Account Snapshot',
            },
        ),
        migrations.CreateModel(
            name='AccountSnapshotHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_snapshot', models.JSONField(default=dict)),
                ('cities', models.JSONField(default=dict)),
                ('military', models.JSONField(default=dict)),
                ('captured_at', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_history', to='accounts.account')),
                ('game_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_history', to='accounts.gameaccount')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['account', '-captured_at'], name='game_accoun_account_8bc4ca_idx'), models.Index(fields=['game_account', '-captured_at'], name='game_accoun_game_ac_97e293_idx')],
            },
        ),
    ]
