# Generated by Django 5.2.14 on 2026-05-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsnapshot',
            name='full_snapshot_updated_at',
            field=models.DateTimeField(blank=True, help_text='Set only by full check_status runs (not partial patches). Runners use this field to determine if a full refresh is needed.', null=True),
        ),
    ]
