# Generated by Django 5.2.14 on 2026-05-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_full_snapshot_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsnapshot',
            name='movements',
            field=models.JSONField(blank=True, default=dict, help_text='Military advisor state — active movements, battles, occupied ports'),
        ),
    ]
