from .constants import (
    CAT_AUTOMATION,
    DONATION_METHOD_CHOICES,
    FIELD_BOOL,
    FIELD_CHOICE,
    FIELD_CITY_SELECT,
    FIELD_DONATION_TYPE,
    FIELD_INT,
)


ACTIONS = {
    1003: {
        "name": "Distribuir em Loop",
        "name_en": "Distribution loop",
        "category": CAT_AUTOMATION,
        "icon": "bi-arrows-expand",
        "runner": "distribute",
        "requires_game_session": True,
        "recurring": True,
        "long_running": True,
        "ready": True,
        "description": "Distribui recursos periodicamente entre cidades.",
        "inputs": [],
    },
    1006: {
        "name": "Doacao em Loop",
        "name_en": "Donation loop",
        "category": CAT_AUTOMATION,
        "icon": "bi-gift",
        "runner": "donate_loop",
        "requires_game_session": True,
        "recurring": True,
        "long_running": True,
        "ready": True,
        "description": "Doa recursos periodicamente em loop.",
        "inputs": [
            {"key": "cities", "type": FIELD_CITY_SELECT, "label": "Cidades", "multiple": True, "required": True},
            {"key": "donation_type", "type": FIELD_DONATION_TYPE, "label": "Destinos da doacao", "required": True, "help": "Selecione floresta, bem comercial ou ambos."},
            {"key": "donation_method", "type": FIELD_CHOICE, "label": "Metodo de calculo", "required": True, "choices": DONATION_METHOD_CHOICES, "default": "2", "help": "Define como a quantidade sera calculada em cada ciclo."},
            {"key": "method_value", "type": FIELD_INT, "label": "Valor do metodo", "required": True, "min": 1, "default": 50, "placeholder": "Ex: 80, 50 ou 10000", "help": "Metodo 1: % maxima do armazem a manter. Metodo 2: % da producao. Metodo 3: quantidade fixa."},
            {"key": "interval_minutes", "type": FIELD_INT, "label": "Intervalo base (min)", "required": True, "min": 1, "default": 1440, "placeholder": "Ex: 1440", "help": "Tempo entre ciclos antes do atraso aleatorio."},
            {"key": "random_wait_minutes", "type": FIELD_INT, "label": "Atraso aleatorio maximo (min)", "required": True, "min": 0, "default": 60, "placeholder": "Ex: 60", "help": "Adiciona um atraso aleatorio de 0 ate esse valor."},
            {"key": "target_level", "type": FIELD_INT, "label": "Parar no nivel", "required": False, "min": 1, "placeholder": "Vazio = infinito", "help": "Opcional. Quando o projeto atingir este nivel, o loop para sozinho."},
            {"key": "post_production_mode", "type": FIELD_CHOICE, "label": "Pos-doacao", "required": True, "default": "preserve", "choices": [("preserve", "Manter % atual"), ("custom", "Usar % customizada")], "help": "Define qual ajuste de producao sera agendado quando a obra entrar em progresso."},
            {"key": "post_sawmill_percent", "type": FIELD_INT, "label": "% Serraria apos doar", "required": False, "min": 0, "max": 150, "default": 150, "placeholder": "Ex: 150"},
            {"key": "post_luxury_percent", "type": FIELD_INT, "label": "% Luxo apos doar", "required": False, "min": 0, "max": 150, "default": 150, "placeholder": "Ex: 150"},
        ],
    },
    1007: {
        "name": "Santuario em Loop",
        "name_en": "Shrine loop",
        "category": CAT_AUTOMATION,
        "icon": "bi-stars",
        "runner": "activate_shrine_loop",
        "requires_game_session": True,
        "recurring": True,
        "long_running": True,
        "ready": True,
        "description": "Mantem os deuses selecionados ativos em loop, respeitando o ciclo do santuario.",
        "inputs": [
            {"key": "god_pan", "type": FIELD_BOOL, "label": "Pan", "required": False, "default": True, "help": "Bencao de madeira."},
            {"key": "god_dionysus", "type": FIELD_BOOL, "label": "Dionisio", "required": False, "default": False, "help": "Bencao de vinho."},
            {"key": "god_tyche", "type": FIELD_BOOL, "label": "Tique", "required": False, "default": False, "help": "Bencao de marmore."},
            {"key": "god_plutus", "type": FIELD_BOOL, "label": "Pluto", "required": False, "default": False, "help": "Bencao de ouro."},
            {"key": "god_theia", "type": FIELD_BOOL, "label": "Teia", "required": False, "default": False, "help": "Bencao de cristal."},
            {"key": "god_hephaestus", "type": FIELD_BOOL, "label": "Hefesto", "required": False, "default": False, "help": "Bencao de enxofre."},
            {"key": "favor_recheck_minutes", "type": FIELD_INT, "label": "Recheck de favor (min)", "required": True, "min": 5, "default": 180, "help": "Se faltar favor, o runner reavalia nesse intervalo."},
            {"key": "cycle_hours", "type": FIELD_INT, "label": "Ciclo do loop (h)", "required": True, "min": 6, "default": 72, "help": "Depois de ativar, agenda o proximo ciclo nesse intervalo."},
        ],
    },
    1301: {
        "name": "Clonar Cidade",
        "name_en": "Clone city",
        "category": CAT_AUTOMATION,
        "icon": "bi-copy",
        "runner": "city_clone",
        "requires_game_session": True,
        "recurring": True,
        "long_running": True,
        "description": "Replica a estrutura de uma cidade em outra.",
        "inputs": [
            {"key": "source_city", "type": FIELD_CITY_SELECT, "label": "Cidade modelo", "multiple": False, "required": True},
            {"key": "target_city", "type": FIELD_CITY_SELECT, "label": "Cidade destino", "multiple": False, "required": True},
            {"key": "max_target_level", "type": FIELD_INT, "label": "Nivel maximo", "required": True, "min": 1, "max": 50},
            {"key": "auto_transport", "type": FIELD_BOOL, "label": "Transportar recursos", "required": False, "default": True},
        ],
    },
    1902: {
        "name": "Rotina Automatica",
        "name_en": "Auto routine",
        "category": CAT_AUTOMATION,
        "icon": "bi-robot",
        "runner": "auto_routine",
        "requires_game_session": True,
        "recurring": True,
        "long_running": True,
        "description": "Executa uma sequencia de acoes automaticamente.",
        "inputs": [],
    },
}
