from .constants import (
    CAT_CONSTRUCTION,
    FIELD_BOOL,
    FIELD_BUILDING_SELECT,
    FIELD_CHOICE,
    FIELD_CITY_SELECT,
    FIELD_INT,
    CONSTRUCTION_TIME_CHOICES,
RESEARCH_REDUCTION_CHOICES,
)

CONSTRUCTION_QUEUE_STRATEGY_CHOICES = [
    ("fifo", "Ordem do plano"),
    ("eta_first", "Menor ETA primeiro"),
    ("smart", "Balanceado (tempo + recursos)"),
]

ACTIONS = {
    1: {
        "name": "Evoluir Construcao",
        "name_en": "Upgrade building",
        "category": CAT_CONSTRUCTION,
        "icon": "bi-arrow-up-circle",
        "runner": "construct_building",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ui_hidden": True,
        "description": "Evolui um edificio existente em uma cidade.",
        "inputs": [
            {"key": "city", "type": FIELD_CITY_SELECT, "label": "Cidade", "multiple": False, "required": True},
            {"key": "building_position", "type": FIELD_BUILDING_SELECT, "label": "Edificio", "required": True, "depends_on": "city"},
            {"key": "target_level", "type": FIELD_INT, "label": "Nivel alvo", "required": True, "min": 1, "max": 86, "default": 1},
            {"key": "research_reduction", "type": FIELD_CHOICE, "label": "Pesquisa economica", "required": False, "default": "14", "choices": RESEARCH_REDUCTION_CHOICES},
            {"key": "build_time_reduction", "type": FIELD_CHOICE, "label": "Modificador de tempo", "required": False, "default": "25", "choices": CONSTRUCTION_TIME_CHOICES},
        ],
    },
    14: {
        "name": "Construir Novo",
        "name_en": "Build new building",
        "category": CAT_CONSTRUCTION,
        "icon": "bi-plus-circle",
        "runner": "construct_building",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ui_hidden": True,
        "description": "Constroi um novo edificio em um slot vazio.",
        "inputs": [
            {"key": "city", "type": FIELD_CITY_SELECT, "label": "Cidade", "multiple": False, "required": True},
            {"key": "building_type", "type": FIELD_CHOICE, "label": "Tipo de edificio", "required": True, "choices": []},
            {"key": "target_level", "type": FIELD_INT, "label": "Nivel alvo", "required": True, "min": 1, "max": 86, "default": 1},
            {"key": "research_reduction", "type": FIELD_CHOICE, "label": "Pesquisa economica", "required": False, "default": "14", "choices": RESEARCH_REDUCTION_CHOICES},
            {"key": "build_time_reduction", "type": FIELD_CHOICE, "label": "Modificador de tempo", "required": False, "default": "25", "choices": CONSTRUCTION_TIME_CHOICES},
        ],
    },
    10: {
        "name": "Demolir Edificio",
        "name_en": "Demolish building",
        "category": CAT_CONSTRUCTION,
        "icon": "bi-trash3",
        "runner": "demolish",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "description": "Demole um edificio existente.",
        "inputs": [
            {"key": "city", "type": FIELD_CITY_SELECT, "label": "Cidade", "multiple": False, "required": True},
            {"key": "building_position", "type": FIELD_BUILDING_SELECT, "label": "Edificio", "required": True, "depends_on": "city"},
        ],
    },
    1001: {
        "name": "Sincronizar Edificios",
        "name_en": "Sync buildings",
        "category": CAT_CONSTRUCTION,
        "icon": "bi-arrow-repeat",
        "runner": "buildings_sync",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ready": True,
        "description": "Sincroniza dados de edificios com o snapshot.",
        "inputs": [],
    },
    1002: {
        "name": "Plano de Construcao",
        "name_en": "Construction plan",
        "category": CAT_CONSTRUCTION,
        "icon": "bi-building-gear",
        "runner": "construction",
        "requires_game_session": True,
        "recurring": True,
        "long_running": True,
        "ready": True,
        "description": "Executa um plano multi-etapa de construcoes, com fila por cidade e reserva de recursos.",
        "inputs": [
            {"key": "auto_transport", "type": FIELD_BOOL, "label": "Transportar recursos automaticamente", "required": False, "default": True},
            {"key": "queue_strategy", "type": FIELD_CHOICE, "label": "Prioridade do plano", "required": False, "default": "eta_first", "choices": CONSTRUCTION_QUEUE_STRATEGY_CHOICES},
            {"key": "research_reduction", "type": FIELD_CHOICE, "label": "Pesquisa economica", "required": False, "default": "14", "choices": RESEARCH_REDUCTION_CHOICES},
        ],
    },
    1004: {
        "name": "Construir Slot",
        "name_en": "Build slot",
        "category": CAT_CONSTRUCTION,
        "icon": "bi-grid-3x3-gap",
        "runner": "construct_building",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ui_hidden": True,
        "description": "Constroi um edificio em um slot especifico.",
        "inputs": [
            {"key": "city", "type": FIELD_CITY_SELECT, "label": "Cidade", "multiple": False, "required": True},
        ],
    },
    820: {
        "name": "Fundar Colonia",
        "name_en": "Found colony",
        "category": CAT_CONSTRUCTION,
        "icon": "bi-signpost-split-fill",
        "runner": "colonize",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ready": True,
        "ui_hidden": True,
        "description": "Abre a tela de colonizacao, valida o slot e envia a fundacao da colonia.",
        "inputs": [
            {"key": "source_city_id", "type": FIELD_CITY_SELECT, "label": "Cidade de origem", "multiple": False, "required": True},
            {"key": "island_id", "type": FIELD_INT, "label": "Ilha alvo", "required": True, "min": 1},
            {"key": "position", "type": FIELD_INT, "label": "Posicao na ilha", "required": True, "min": 0, "max": 16},
            {"key": "wood", "type": FIELD_INT, "label": "Madeira extra", "required": False, "min": 0, "default": 0},
            {"key": "wine", "type": FIELD_INT, "label": "Vinho extra", "required": False, "min": 0, "default": 0},
            {"key": "marble", "type": FIELD_INT, "label": "Marmore extra", "required": False, "min": 0, "default": 0},
            {"key": "crystal", "type": FIELD_INT, "label": "Cristal extra", "required": False, "min": 0, "default": 0},
            {"key": "sulfur", "type": FIELD_INT, "label": "Enxofre extra", "required": False, "min": 0, "default": 0},
        ],
    },
}
