from .constants import (
    CAT_AUTOMATION,
    CAT_ECONOMY,
    DISTRIBUTION_STRATEGY_CHOICES,
    DONATION_METHOD_CHOICES,
    FIELD_BOOL,
    FIELD_CHOICE,
    FIELD_CITY_SELECT,
    FIELD_DONATION_TYPE,
    FIELD_INT,
    TRANSPORT_LOAD_CHOICES,
)


ACTIONS = {
    6: {
        "name": "Login Diario",
        "name_en": "Daily login",
        "category": CAT_ECONOMY,
        "icon": "bi-box-arrow-in-right",
        "runner": "login_daily",
        "requires_game_session": True,
        "recurring": True,
        "long_running": True,
        "ready": True,
        "description": "Coleta bonus de login diario.",
        "inputs": [
            {"key": "city", "type": FIELD_CITY_SELECT, "label": "Cidade do bonus", "multiple": False, "required": True, "help": "Cidade que recebe o bonus diario de vinho."},
            {"key": "collect_favor", "type": FIELD_BOOL, "label": "Coletar favor das tarefas", "required": False, "default": True, "help": "Recolhe automaticamente as tasks concluidas na tela diaria."},
            {"key": "collect_fountain", "type": FIELD_BOOL, "label": "Coletar fonte de ambrosia", "required": False, "default": True, "help": "Tenta coletar a fonte se ela estiver ativa na cidade escolhida."},
            {"key": "fallback_interval_hours", "type": FIELD_INT, "label": "Intervalo fallback (h)", "required": True, "min": 1, "default": 24, "help": "Usado quando o jogo nao informar o countdown real ate o proximo reset."},
            {"key": "reschedule_margin_minutes", "type": FIELD_INT, "label": "Margem apos reset (min)", "required": True, "min": 0, "default": 15, "help": "Tempo extra somado ao countdown real para o proximo ciclo."},
        ],
    },
    901: {
        "name": "Doacao",
        "name_en": "Single donation",
        "category": CAT_ECONOMY,
        "icon": "bi-gift",
        "runner": "donate",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ready": True,
        "description": "Doa recursos para a floresta, bem comercial ou ambos.",
        "inputs": [
            {"key": "cities", "type": FIELD_CITY_SELECT, "label": "Cidades", "multiple": True, "required": True, "help": "Selecione uma ou mais cidades para doar."},
            {"key": "donation_type", "type": FIELD_DONATION_TYPE, "label": "Destinos da doacao", "required": True, "help": "Selecione floresta, bem comercial ou ambos."},
            {"key": "amount", "type": FIELD_INT, "label": "Quantidade", "required": True, "min": 1, "placeholder": "Ex: 50000", "help": "Quantidade por cidade."},
        ],
    },
    902: {
        "name": "Doacao Automatica",
        "name_en": "Auto donation",
        "category": CAT_AUTOMATION,
        "icon": "bi-gift",
        "runner": "donate_loop",
        "requires_game_session": True,
        "recurring": True,
        "long_running": True,
        "ready": True,
        "description": "Doa recursos periodicamente em loop.",
        "ui_hidden": True,
        "inputs": [
            {"key": "cities", "type": FIELD_CITY_SELECT, "label": "Cidades", "multiple": True, "required": True},
            {"key": "donation_type", "type": FIELD_DONATION_TYPE, "label": "Destinos da doacao", "required": True, "help": "Selecione floresta, bem comercial ou ambos."},
            {"key": "donation_method", "type": FIELD_CHOICE, "label": "Metodo de calculo", "required": True, "choices": DONATION_METHOD_CHOICES, "default": "2", "help": "Define como a quantidade sera calculada em cada ciclo."},
            {"key": "method_value", "type": FIELD_INT, "label": "Valor do metodo", "required": True, "min": 1, "default": 50, "placeholder": "Ex: 80, 50 ou 10000", "help": "Metodo 1: % maxima do armazem a manter. Metodo 2: % da producao. Metodo 3: quantidade fixa."},
            {"key": "interval_minutes", "type": FIELD_INT, "label": "Intervalo base (min)", "required": True, "min": 1, "default": 1440, "placeholder": "Ex: 1440", "help": "Tempo entre ciclos antes do atraso aleatorio."},
            {"key": "random_wait_minutes", "type": FIELD_INT, "label": "Atraso aleatorio maximo (min)", "required": True, "min": 0, "default": 60, "placeholder": "Ex: 60", "help": "Adiciona um atraso aleatorio de 0 ate esse valor."},
            {"key": "target_level", "type": FIELD_INT, "label": "Parar no nivel", "required": False, "min": 1, "placeholder": "Vazio = infinito", "help": "Opcional. Quando o projeto atingir este nivel, o loop para sozinho."},
            {"key": "post_production_mode", "type": FIELD_CHOICE, "label": "Pos-doacao", "required": True, "default": "preserve", "choices": [("preserve", "Manter % atual"), ("custom", "Usar % customizada")], "help": "Define qual ajuste de producao sera agendado quando a obra entrar em progresso."},
            {"key": "post_sawmill_percent", "type": FIELD_INT, "label": "% Serraria apos doar", "required": False, "min": 0, "max": 150, "default": 150, "placeholder": "Ex: 150"},
            {"key": "post_luxury_percent", "type": FIELD_INT, "label": "% Luxo apos doar", "required": False, "min": 0, "max": 150, "default": 150, "placeholder": "Ex: 150"},
        ],
    },
    2: {
        "name": "Enviar Recursos",
        "name_en": "Send resources",
        "category": CAT_ECONOMY,
        "icon": "bi-truck",
        "runner": "send_resources",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ready": True,
        "description": "Envia recursos de uma cidade para outra.",
        "inputs": [
            {"key": "from_city", "type": FIELD_CITY_SELECT, "label": "Cidade de origem", "multiple": False, "required": True},
            {"key": "to_city", "type": FIELD_CITY_SELECT, "label": "Cidade de destino", "multiple": False, "required": True},
            {"key": "transport_load_percent", "type": FIELD_CHOICE, "label": "Carga por barco", "required": True, "choices": TRANSPORT_LOAD_CHOICES, "default": "100", "help": "Menor carga por barco pode reduzir o tempo de viagem em rotas longas, mas tambem reduz a capacidade total imediata."},
            {"key": "use_freighters", "type": FIELD_BOOL, "label": "Usar cargueiros (freighters)", "required": False, "default": False, "help": "Cargueiros tem mais capacidade que mercantes mas exigem pesquisa. Se desativado, usa mercantes normais."},
            {"key": "confirm_arrival", "type": FIELD_BOOL, "label": "Confirmar chegada automaticamente", "required": False, "default": True, "help": "Cria um monitor de chegada apos o envio."},
            {"key": "confirmation_margin_minutes", "type": FIELD_INT, "label": "Margem da confirmacao (min)", "required": True, "min": 0, "default": 2, "help": "Tempo extra apos o ETA total antes do primeiro check de chegada."},
            {"key": "wood", "type": FIELD_INT, "label": "Madeira", "required": False, "min": 0, "default": 0},
            {"key": "wine", "type": FIELD_INT, "label": "Vinho", "required": False, "min": 0, "default": 0},
            {"key": "marble", "type": FIELD_INT, "label": "Marmore", "required": False, "min": 0, "default": 0},
            {"key": "crystal", "type": FIELD_INT, "label": "Cristal", "required": False, "min": 0, "default": 0},
            {"key": "sulfur", "type": FIELD_INT, "label": "Enxofre", "required": False, "min": 0, "default": 0},
        ],
    },
    3: {
        "name": "Distribuir Recursos",
        "name_en": "Distribute resources",
        "category": CAT_ECONOMY,
        "icon": "bi-arrows-expand",
        "runner": "distribute",
        "requires_game_session": True,
        "recurring": True,
        "long_running": False,
        "ready": True,
        "description": "Planeja e distribui recursos entre cidades, consolidando remessas por rota.",
        "inputs": [
            {"key": "cities", "type": FIELD_CITY_SELECT, "label": "Cidades participantes", "multiple": True, "required": True, "help": "Selecione as cidades que entram no planejamento logistico."},
            {"key": "strategy", "type": FIELD_CHOICE, "label": "Estrategia", "required": True, "choices": DISTRIBUTION_STRATEGY_CHOICES, "default": "targets", "help": "Define como escolher origens e destinos no ciclo."},
            {"key": "wood", "type": FIELD_BOOL, "label": "Madeira", "required": False, "default": True},
            {"key": "wine", "type": FIELD_BOOL, "label": "Vinho", "required": False, "default": False},
            {"key": "marble", "type": FIELD_BOOL, "label": "Marmore", "required": False, "default": False},
            {"key": "crystal", "type": FIELD_BOOL, "label": "Cristal", "required": False, "default": False},
            {"key": "sulfur", "type": FIELD_BOOL, "label": "Enxofre", "required": False, "default": False},
            {"key": "minimum_stock", "type": FIELD_INT, "label": "Minimo por cidade", "required": True, "min": 0, "default": 20000, "help": "Quando uma cidade estiver abaixo disso, ela vira prioridade de recebimento."},
            {"key": "target_stock", "type": FIELD_INT, "label": "Alvo por cidade", "required": True, "min": 0, "default": 60000, "help": "Objetivo de estoque por recurso nas cidades atendidas."},
            {"key": "origin_reserve_stock", "type": FIELD_INT, "label": "Reserva minima na origem", "required": True, "min": 0, "default": 50000, "help": "Quantidade que a cidade doadora sempre deve preservar."},
            {"key": "useful_transfer_min", "type": FIELD_INT, "label": "Envio minimo util", "required": True, "min": 1, "default": 5000, "help": "Evita criar remessas pequenas demais."},
            {"key": "shipment_cap", "type": FIELD_INT, "label": "Envio maximo por rota", "required": True, "min": 1, "default": 50000, "help": "Limite total por remessa consolidada."},
            {"key": "max_routes_per_cycle", "type": FIELD_INT, "label": "Maximo de rotas por ciclo", "required": True, "min": 1, "default": 5, "help": "Limita quantas remessas serao criadas em cada execucao."},
            {"key": "transport_load_percent", "type": FIELD_CHOICE, "label": "Carga por barco", "required": True, "choices": TRANSPORT_LOAD_CHOICES, "default": "100", "help": "Ajusta capacidade x velocidade das remessas filhas."},
            {"key": "freighter_threshold", "type": FIELD_INT, "label": "Mínimo de cargo pra usar cargueiro", "required": True, "min": 0, "default": 30000, "help": "Cargo desse valor ou mais usa cargueiro (1 cargueiro = 50k). Resto vai mercante. Default 30k."},
            {"key": "confirm_arrival", "type": FIELD_BOOL, "label": "Confirmar chegada automaticamente", "required": False, "default": True},
            {"key": "confirmation_margin_minutes", "type": FIELD_INT, "label": "Margem da confirmacao (min)", "required": True, "min": 0, "default": 2},
            {"key": "loop_enabled", "type": FIELD_BOOL, "label": "Executar em loop", "required": False, "default": True, "help": "Se ativo, o runner se reagenda dinamicamente."},
            {"key": "min_recheck_minutes", "type": FIELD_INT, "label": "Rechecagem minima (min)", "required": True, "min": 1, "default": 30},
            {"key": "max_recheck_minutes", "type": FIELD_INT, "label": "Rechecagem maxima (min)", "required": True, "min": 5, "default": 720},
        ],
    },
    22: {
        "name": "Consolidar Recursos",
        "name_en": "Consolidate resources",
        "category": CAT_ECONOMY,
        "icon": "bi-arrows-collapse",
        "runner": "consolidate",
        "requires_game_session": True,
        "recurring": True,
        "long_running": False,
        "ui_hidden": True,
        "description": "Concentra recursos de varias cidades em uma.",
        "inputs": [
            {"key": "target_city", "type": FIELD_CITY_SELECT, "label": "Cidade destino", "multiple": False, "required": True},
        ],
    },
    23: {
        "name": "Alterar Producao",
        "name_en": "Modify production",
        "category": CAT_ECONOMY,
        "icon": "bi-sliders2",
        "runner": "modify_production",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ready": True,
        "description": "Ajusta a proporcao de trabalhadores na serraria e recurso de luxo.",
        "inputs": [
            {"key": "cities", "type": FIELD_CITY_SELECT, "label": "Cidades", "multiple": True, "required": False, "help": "Vazio = todas as cidades."},
            {"key": "sawmill_percent", "type": FIELD_INT, "label": "% Serraria", "required": True, "min": 0, "max": 150, "placeholder": "Ex: 50"},
            {"key": "luxury_percent", "type": FIELD_INT, "label": "% Recurso de luxo", "required": True, "min": 0, "max": 150, "placeholder": "Ex: 80"},
        ],
    },
    5: {
        "name": "Ativar Santuario",
        "name_en": "Activate shrine",
        "category": CAT_ECONOMY,
        "icon": "bi-stars",
        "runner": "activate_shrine",
        "requires_game_session": True,
        "recurring": False,
        "long_running": True,
        "ready": True,
        "description": "Ativa os deuses selecionados uma vez, aguardando favor se necessario.",
        "inputs": [
            {"key": "god_pan", "type": FIELD_BOOL, "label": "Pan", "required": False, "default": True, "help": "Bencao de madeira."},
            {"key": "god_dionysus", "type": FIELD_BOOL, "label": "Dionisio", "required": False, "default": False, "help": "Bencao de vinho."},
            {"key": "god_tyche", "type": FIELD_BOOL, "label": "Tique", "required": False, "default": False, "help": "Bencao de marmore."},
            {"key": "god_plutus", "type": FIELD_BOOL, "label": "Pluto", "required": False, "default": False, "help": "Bencao de ouro."},
            {"key": "god_theia", "type": FIELD_BOOL, "label": "Teia", "required": False, "default": False, "help": "Bencao de cristal."},
            {"key": "god_hephaestus", "type": FIELD_BOOL, "label": "Hefesto", "required": False, "default": False, "help": "Bencao de enxofre."},
            {"key": "favor_recheck_minutes", "type": FIELD_INT, "label": "Recheck de favor (min)", "required": True, "min": 5, "default": 180, "help": "Se faltar favor, o job tenta de novo depois desse intervalo."},
        ],
    },
    11: {
        "name": "Ativar Milagre",
        "name_en": "Activate miracle",
        "category": CAT_ECONOMY,
        "icon": "bi-lightning-charge",
        "runner": "activate_miracle",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ready": True,
        "description": "Ativa o milagre da ilha de uma cidade.",
        "inputs": [
            {"key": "city", "type": FIELD_CITY_SELECT, "label": "Cidade", "multiple": False, "required": True},
        ],
    },
    18: {
        "name": "Pesquisar",
        "name_en": "Research",
        "category": CAT_ECONOMY,
        "icon": "bi-mortarboard",
        "runner": "research",
        "requires_game_session": True,
        "recurring": True,
        "long_running": True,
        "ready": True,
        "description": "Monitora os ramos selecionados, prioriza o menor ETA e segue ate o maximo.",
        "inputs": [
            {"key": "branch_seafaring", "type": FIELD_BOOL, "label": "Navegacao Maritima", "required": False, "default": True},
            {"key": "branch_economy", "type": FIELD_BOOL, "label": "Economia", "required": False, "default": True},
            {"key": "branch_knowledge", "type": FIELD_BOOL, "label": "Ciencia", "required": False, "default": True},
            {"key": "branch_military", "type": FIELD_BOOL, "label": "Militar", "required": False, "default": True},
            {"key": "branch_mythology", "type": FIELD_BOOL, "label": "Mitologia", "required": False, "default": True},
            {"key": "fallback_interval_minutes", "type": FIELD_INT, "label": "Fallback (min)", "required": True, "min": 5, "default": 60, "help": "Usado quando o jogo nao informar um ETA confiavel."},
            {"key": "ready_margin_minutes", "type": FIELD_INT, "label": "Margem apos ETA (min)", "required": True, "min": 0, "default": 10, "help": "Tempo extra somado ao ETA antes do proximo check."},
        ],
    },
    26: {
        "name": "Conduzir Ensaio",
        "name_en": "Conduct experiment",
        "category": CAT_ECONOMY,
        "icon": "bi-gem",
        "runner": "buy_research",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ready": True,
        "description": "Consome cristal em uma academia para gerar pontos de pesquisa.",
        "inputs": [
            {"key": "city", "type": FIELD_CITY_SELECT, "label": "Cidade", "multiple": False, "required": True, "help": "Idealmente uma cidade de cristal com academia."},
            {"key": "use_athena_scroll", "type": FIELD_BOOL, "label": "Usar Pergaminho de Atena", "required": False, "default": False, "help": "Usa o custo com desconto quando o pergaminho estiver disponivel."},
            {"key": "pay_with_ambrosia", "type": FIELD_BOOL, "label": "Permitir ambrosia", "required": False, "default": False, "help": "Mantido desligado por padrao."},
        ],
    },
    27: {
        "name": "Ajustar Cientistas",
        "name_en": "Adjust scientists",
        "category": CAT_ECONOMY,
        "icon": "bi-people",
        "runner": "adjust_scientists",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ready": True,
        "description": "Define a quantidade de cientistas nas academias selecionadas.",
        "inputs": [
            {"key": "cities", "type": FIELD_CITY_SELECT, "label": "Cidades", "multiple": True, "required": False, "help": "Vazio = todas as cidades com academia."},
            {"key": "target_mode", "type": FIELD_CHOICE, "label": "Modo do alvo", "required": True, "default": "absolute", "choices": [("absolute", "Quantidade fixa"), ("percent_max", "% do maximo")], "help": "Aplica o mesmo criterio em todas as academias selecionadas."},
            {"key": "target_value", "type": FIELD_INT, "label": "Valor do alvo", "required": True, "min": 0, "default": 0, "help": "Quantidade fixa ou percentual do maximo, conforme o modo."},
            {"key": "reserve_citizens", "type": FIELD_INT, "label": "Reserva de cidadaos", "required": True, "min": 0, "default": 0, "help": "Evita consumir os ultimos cidadaos livres da cidade."},
        ],
    },
    25: {
        "name": "Modo Ferias",
        "name_en": "Vacation Mode",
        "category": CAT_ECONOMY,
        "icon": "bi-umbrella-fill",
        "runner": "vacation_mode",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ready": True,
        "description": "Ativa ou desativa o modo ferias da conta. Em ferias, nao ha custos de manutencao de tropas.",
        "inputs": [
            {"key": "enable", "type": FIELD_BOOL, "label": "Ativar modo ferias", "required": False, "default": True, "help": "True = ativar, False = desativar."},
        ],
    },
}
