from .constants import CAT_AUTOMATION, CAT_MILITARY, FIELD_CHOICE, FIELD_CITY_SELECT


ACTIONS = {
    1005: {
        "name": "Treinar Unidades",
        "name_en": "Train units",
        "category": CAT_MILITARY,
        "icon": "bi-people-fill",
        "runner": "train",
        "requires_game_session": True,
        "recurring": True,
        "long_running": False,
        "description": "Treina tropas ou navios em uma cidade.",
        "inputs": [
            {"key": "city", "type": FIELD_CITY_SELECT, "label": "Cidade", "multiple": False, "required": True},
        ],
    },
    1202: {
        "name": "Estacionar Unidades",
        "name_en": "Station units",
        "category": CAT_MILITARY,
        "icon": "bi-geo-alt-fill",
        "runner": "station",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "description": "Estaciona tropas em outra cidade.",
        "inputs": [],
    },
    1203: {
        "name": "Melhorar Unidades",
        "name_en": "Upgrade units",
        "category": CAT_AUTOMATION,
        "icon": "bi-arrow-up-square",
        "runner": "upgrade_units",
        "requires_game_session": True,
        "recurring": True,
        "long_running": False,
        "ready": True,
        "description": "Pesquisa melhorias de unidades na Oficina do Inventor automaticamente. Selecione quais unidades evoluir, nivel maximo e reservas de recursos.",
        "inputs": [
            {
                "key": "city_id",
                "type": FIELD_CITY_SELECT,
                "label": "Cidade",
                "multiple": False,
                "required": False,
                "help": "Deixe em branco para processar todas as cidades que possuem Oficina do Inventor.",
            },
        ],
    },
    17: {
        "name": "Pirata Automatico",
        "name_en": "Auto pirate",
        "category": CAT_MILITARY,
        "icon": "bi-flag-fill",
        "runner": "pirate",
        "requires_game_session": True,
        "recurring": True,
        "long_running": True,
        "description": "Executa missoes piratas automaticamente.",
        "inputs": [],
    },
    15: {
        "name": "Investigar",
        "name_en": "Investigate",
        "category": CAT_MILITARY,
        "icon": "bi-binoculars",
        "runner": "investigate",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "description": "Investiga uma cidade inimiga.",
        "inputs": [],
    },
    9002: {
        "name": "Revolta",
        "name_en": "Revolt",
        "category": CAT_MILITARY,
        "icon": "bi-flag-fill",
        "runner": "revolt",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ready": True,
        "description": "Inicia uma revolta para libertar cidade ocupada ou porto bloqueado por inimigo.",
        "inputs": [
            {
                "key": "city_id",
                "type": FIELD_CITY_SELECT,
                "label": "Cidade",
                "multiple": False,
                "required": True,
                "help": "Selecione a cidade com ocupacao terrestre ou bloqueio naval.",
            },
            {
                "key": "revolt_type",
                "type": FIELD_CHOICE,
                "label": "Tipo de revolta",
                "required": True,
                "default": "troops",
                "choices": [
                    ("troops", "Forcas de ocupacao (tropas)"),
                    ("ships", "Bloqueio do porto (frotas)"),
                ],
                "help": "Escolha se a revolta deve mirar tropas em terra ou a frota que bloqueia o porto.",
            },
        ],
    },
}
