from .constants import CAT_AUTOMATION, CAT_MILITARY, FIELD_BOOL, FIELD_CHOICE, FIELD_CITY_SELECT, FIELD_INT, FIELD_JSON_ARRAY, FIELD_STR


ACTIONS = {
    13: {
        "name": "Movimentos de Navios",
        "name_en": "Ship movements",
        "category": CAT_MILITARY,
        "icon": "bi-radar",
        "runner": "military_movements",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ready": True,
        "description": (
            "Lê o conselheiro militar uma vez e salva o estado "
            "(movimentos ativos, batalhas, portos ocupados, conteúdo dos barcos) "
            "no snapshot. Disparado automaticamente antes de cada raid alert."
        ),
        "inputs": [],
    },
    19: {
        "name": "Roubar Bárbaros",
        "name_en": "Raid Barbarians",
        "category": CAT_MILITARY,
        "icon": "bi-lightning-charge-fill",
        "runner": "barbarians",
        "requires_game_session": True,
        "recurring": True,
        "long_running": False,
        "ready": True,
        "description": (
            "Ataca vilas de bárbaros automaticamente e envia saqueadores após a vitória. "
            "Suporta múltiplas ilhas em rotação, filtro de nível e threshold de recursos."
        ),
        "inputs": [
            {
                "key": "city_id",
                "type": FIELD_CITY_SELECT,
                "label": "Cidade de partida",
                "multiple": False,
                "required": True,
                "help": "Cidade onde estão as tropas que farão o ataque.",
            },
            {
                "key": "island_ids",
                "type": FIELD_STR,
                "label": "ID(s) da ilha",
                "required": True,
                "help": "Um ou mais IDs de ilhas separados por vírgula. Ex: 12345,67890. O ataque rotaciona entre elas.",
            },
            {
                "key": "troop_mode",
                "type": FIELD_CHOICE,
                "label": "Modo de tropas",
                "required": True,
                "default": "schematic",
                "choices": [
                    ("schematic", "Esquema automático (igual ao ikabot)"),
                    ("available", "Todas as tropas disponíveis"),
                    ("custom", "Personalizado (JSON)"),
                ],
                "help": "Esquema automático usa tabelas predefinidas por nível. 'Todas disponíveis' envia tudo que tem. 'Personalizado' usa o JSON abaixo.",
            },
            {
                "key": "custom_troops",
                "type": FIELD_STR,
                "label": "Tropas personalizadas (JSON)",
                "required": False,
                "help": 'Só usado no modo personalizado. Ex: {"302": 90, "304": 21}',
            },
            {
                "key": "loot",
                "type": FIELD_BOOL,
                "label": "Fase de saque (enviar saqueadores após vitória)",
                "required": False,
                "default": True,
            },
            {
                "key": "min_barb_level",
                "type": FIELD_INT,
                "label": "Nível mínimo de bárbaros para atacar",
                "required": False,
                "default": 1,
                "min": 1,
                "max": 99,
                "help": "Ignora ilhas abaixo deste nível (bárbaros fracos = pouco recurso).",
            },
            {
                "key": "max_barb_level",
                "type": FIELD_INT,
                "label": "Nível máximo de bárbaros para atacar",
                "required": False,
                "default": 99,
                "min": 1,
                "max": 99,
                "help": "Ignora ilhas acima deste nível (bárbaros fortes demais para as tropas disponíveis).",
            },
            {
                "key": "min_resources",
                "type": FIELD_INT,
                "label": "Recursos mínimos na vila para valer atacar",
                "required": False,
                "default": 0,
                "min": 0,
                "help": "Pula o ataque se o total de recursos na vila for menor que este valor. 0 = sem filtro.",
            },
            {
                "key": "extra_ships",
                "type": FIELD_INT,
                "label": "Navios extras (além do mínimo calculado)",
                "required": False,
                "default": 0,
                "min": 0,
                "max": 50,
            },
            {
                "key": "recheck_minutes",
                "type": FIELD_INT,
                "label": "Intervalo de verificação durante batalha (min)",
                "required": False,
                "default": 15,
                "min": 5,
                "max": 120,
                "help": "A cada round de batalha demora ~15 min. Valores menores consomem mais requests.",
            },
            {
                "key": "max_random_wait",
                "type": FIELD_INT,
                "label": "Espera aleatória máxima anti-detecção (segundos)",
                "required": False,
                "default": 0,
                "min": 0,
                "max": 3600,
                "help": "Aguarda um tempo aleatório de 0 a N segundos antes de cada ataque.",
            },
        ],
    },
    806: {
        "name": "Banco de Generais — Gerenciar",
        "name_en": "Generals Bank — Manage",
        "category": CAT_MILITARY,
        "icon": "bi-shield-fill-check",
        "runner": "generals_bank_manage",
        "requires_game_session": True,
        "recurring": False,
        "long_running": True,
        "ui_hidden": True,
        "description": "Orquestra um ciclo completo do banco de generais: decide modo, dispara produtoras, aguarda conclusão e ativa compra.",
        "inputs": [],
    },
    809: {
        "name": "Banco de Generais — Tarefa da Produtora",
        "name_en": "Generals Bank — Producer task",
        "category": CAT_MILITARY,
        "icon": "bi-diagram-3-fill",
        "runner": "generals_bank_producer_task",
        "requires_game_session": True,
        "recurring": False,
        "long_running": True,
        "ui_hidden": True,
        "description": "Executa uma tarefa de producao do banco de generais: treina unidades na produtora e lista no Mercado Negro.",
        "inputs": [],
    },
    807: {
        "name": "Banco de Generais — Comprar",
        "name_en": "Generals Bank — Buy",
        "category": CAT_MILITARY,
        "icon": "bi-shield-plus",
        "runner": "generals_bank_buy",
        "requires_game_session": True,
        "recurring": False,
        "long_running": True,
        "ui_hidden": True,
        "description": "Conta banco sai de férias, compra unidades dos produtores e volta a dormir.",
        "inputs": [],
    },

    1005: {
        "name": "Gerenciar Treino Militar",
        "name_en": "Manage military training",
        "category": CAT_MILITARY,
        "icon": "bi-people-fill",
        "runner": "train_units",
        "requires_game_session": True,
        "recurring": True,
        "long_running": False,
        "ready": True,
        "description": "Treina tropas ou navios em uma cidade. Suporta treino único ou manutenção automática de efetivo.",
        "inputs": [
            {"key": "city_id", "type": FIELD_CITY_SELECT, "label": "Cidade", "multiple": False, "required": False},
            {"key": "building_type", "type": FIELD_CHOICE, "label": "Tipo", "required": True,
             "default": "troops", "choices": [("troops", "Tropas (Quartel)"), ("fleet", "Frotas (Estaleiro)")]},
            {"key": "mode", "type": FIELD_CHOICE, "label": "Modo", "required": True,
             "default": "once", "choices": [("once", "Treinar agora"), ("distribute", "Distribuir treino"), ("maintain", "Manter efetivo")]},
            {"key": "maintain_scope", "type": FIELD_CHOICE, "label": "Escopo da manutencao", "required": False,
             "default": "local", "choices": [("local", "Cidade unica"), ("selected_uniform", "Mesmo alvo em cidades selecionadas"), ("selected_custom", "Alvo customizado por cidade")]},
            {"key": "consolidate_city_id", "type": FIELD_CITY_SELECT, "label": "Consolidar em", "multiple": False, "required": False},
            {"key": "position", "type": FIELD_INT, "label": "Posição do edifício", "required": False, "default": 0,
             "help": "Posição do Quartel/Estaleiro no mapa da cidade (0 = detectar automaticamente)."},
            {"key": "recheck_minutes", "type": FIELD_INT, "label": "Verificar a cada (min)", "required": False,
             "default": 120, "min": 30, "help": "Apenas no modo Manter efetivo."},
        ],
    },
    1202: {
        "name": "Mover Forcas",
        "name_en": "Move forces",
        "category": CAT_MILITARY,
        "icon": "bi-geo-alt-fill",
        "runner": "station_units",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ready": True,
        "description": "Move tropas terrestres de uma cidade para guarnecer outra.",
        "inputs": [
            {"key": "scope", "type": FIELD_CHOICE, "label": "Tipo", "required": True,
             "default": "troops", "choices": [("troops", "Tropas"), ("fleet", "Frotas")]},
            {"key": "from_city_id", "type": FIELD_CITY_SELECT, "label": "Cidade de origem", "multiple": False, "required": True},
            {"key": "to_city_id", "type": FIELD_CITY_SELECT, "label": "Cidade de destino", "multiple": False, "required": True},
        ],
    },
    1203: {
        "name": "Melhorar Unidades",
        "name_en": "Upgrade units",
        "category": CAT_AUTOMATION,
        "icon": "bi-arrow-up-square",
        "runner": "upgrade_units",
        "requires_game_session": True,
        "recurring": True,
        "long_running": False,
        "ready": True,
        "description": "Pesquisa melhorias de unidades na Oficina do Inventor automaticamente. Selecione quais unidades evoluir, nivel maximo e reservas de recursos.",
        "inputs": [
            {
                "key": "city_id",
                "type": FIELD_CITY_SELECT,
                "label": "Cidade",
                "multiple": False,
                "required": False,
                "help": "Deixe em branco para processar todas as cidades que possuem Oficina do Inventor.",
            },
            {
                "key": "target_all",
                "type": FIELD_BOOL,
                "label": "Melhorar todas as unidades disponiveis",
                "required": False,
                "default": True,
                "help": "Se marcado, ignora a lista unit_targets e melhora todas as unidades desbloqueadas.",
            },
            {
                "key": "unit_targets",
                "type": FIELD_JSON_ARRAY,
                "label": "Unidades alvo (JSON)",
                "required": False,
                "help": 'Lista JSON de {"key": "hoplite", "attack_max": N, "defense_max": N}. Ignorado se target_all=True.',
            },
            {
                "key": "min_crystal_reserve",
                "type": FIELD_INT,
                "label": "Reserva minima de cristal",
                "required": False,
                "default": 0,
                "min": 0,
                "help": "Nao gasta se o estoque de cristal ficaria abaixo desse valor.",
            },
            {
                "key": "min_gold_reserve",
                "type": FIELD_INT,
                "label": "Reserva minima de ouro",
                "required": False,
                "default": 0,
                "min": 0,
                "help": "Nao gasta se o saldo de ouro ficaria abaixo desse valor.",
            },
            {
                "key": "priority_mode",
                "type": FIELD_CHOICE,
                "label": "Ordem de prioridade",
                "required": False,
                "default": "offensive_first",
                "choices": [
                    ("offensive_first", "Ofensivo primeiro"),
                    ("defensive_first", "Defensivo primeiro"),
                    ("shortest_first", "Mais rapida primeiro"),
                    ("cheapest_first", "Mais barata primeiro"),
                ],
            },
        ],
    },
    17: {
        "name": "Pirata Automatico",
        "name_en": "Auto Pirate",
        "category": CAT_MILITARY,
        "icon": "bi-flag-fill",
        "runner": "pirate",
        "requires_game_session": True,
        "recurring": True,
        "long_running": True,
        "ready": True,
        "description": "Envia a tripulacao em missoes piratas automaticamente e converte pontos de captura em forca da tripulacao.",
        "inputs": [
            {"key": "city_id", "type": FIELD_CITY_SELECT, "label": "Cidade (com Fortaleza Pirata)", "multiple": False, "required": True, "city_building": "pirateFortress"},
            # Missão simples (sem agendamento por horário)
            {"key": "mission_level", "type": FIELD_INT, "label": "Nível da missão", "required": True, "default": 7,
             "help": "Nível de fortaleza para a missão (1,3,5,7,9,11,13,15,17). Ignorado se agendamento por horário estiver ativo."},
            # Agendamento por horário (dia vs noite)
            {"key": "schedule_by_time", "type": FIELD_BOOL, "label": "Agendar por horário (missão diferente de dia e de noite)", "required": False, "default": False},
            {"key": "day_mission_level",  "type": FIELD_INT, "label": "Missão de dia — nível",           "required": False, "default": 7},
            {"key": "day_start_hour",     "type": FIELD_INT, "label": "Missão de dia — hora início",     "required": False, "default": 8,  "min": 0, "max": 23},
            {"key": "day_end_hour",       "type": FIELD_INT, "label": "Missão de dia — hora fim",        "required": False, "default": 22, "min": 0, "max": 23},
            {"key": "night_mission_level","type": FIELD_INT, "label": "Missão de noite — nível",         "required": False, "default": 13},
            {"key": "night_start_hour",   "type": FIELD_INT, "label": "Missão de noite — hora início",   "required": False, "default": 22, "min": 0, "max": 23},
            {"key": "night_end_hour",     "type": FIELD_INT, "label": "Missão de noite — hora fim",      "required": False, "default": 8,  "min": 0, "max": 23},
            # Espera aleatória (anti-detecção)
            {"key": "max_random_wait", "type": FIELD_INT, "label": "Espera aleatória máxima (segundos)", "required": False, "default": 0,
             "min": 0, "max": 3600, "help": "Aguarda um tempo aleatório de 0 a N segundos antes de iniciar cada missão."},
            # Conversão de pontos
            {"key": "convert_mode", "type": FIELD_CHOICE, "label": "Conversão de pontos de captura", "required": True, "default": "all",
             "choices": [
                 ("never",     "Nunca converter"),
                 ("all",       "Converter tudo após cada missão"),
                 ("percent",   "Converter X% do ganho da missão"),
                 ("threshold", "Converter quando atingir mínimo de pontos"),
             ]},
            {"key": "convert_percent",   "type": FIELD_INT, "label": "Percentual a converter (%)", "required": False, "default": 100,
             "min": 1, "max": 100, "help": "Só usado no modo porcentagem. Aplica sobre o ganho da missão recém-concluída, não sobre o saldo total."},
            {"key": "convert_threshold", "type": FIELD_INT, "label": "Mínimo de pontos para converter", "required": False, "default": 500,
             "min": 1, "help": "Só usado no modo mínimo."},
            # Ciclo especial (targeted)
            {"key": "enable_targeted_cycle", "type": FIELD_BOOL, "label": "Ativar ciclo especial (colonizar + raid)", "required": False, "default": False,
             "help": "Coloniza na ilha do alvo do ranking pirata, constrói fortaleza temporária, executa raid e abandona."},
            {"key": "targeted_interval_days", "type": FIELD_INT, "label": "Ciclo especial — intervalo mínimo (dias)", "required": False, "default": 7,
             "min": 1, "help": "Dias mínimos entre cada ciclo especial."},
            {"key": "targeted_after_hour", "type": FIELD_INT, "label": "Ciclo especial — hora mínima para iniciar", "required": False, "default": 16,
             "min": 0, "max": 23, "help": "Só inicia o ciclo especial a partir desta hora (horário local do servidor)."},
            {"key": "targeted_max_travel_hours", "type": FIELD_INT, "label": "Ciclo especial — viagem máxima (horas)", "required": False, "default": 12,
             "min": 1, "max": 48, "help": "Cancela o ciclo se o tempo de viagem da colônia exceder este limite. 0 = sem limite."},
            {"key": "targeted_max_active_foundations", "type": FIELD_INT, "label": "Ciclo especial — máx. colônias temporárias simultâneas", "required": False, "default": 1,
             "min": 1, "max": 5},
            {"key": "target_require_lower_total_score", "type": FIELD_BOOL, "label": "Ciclo especial — exigir pontuação total menor que a minha", "required": False, "default": True},
            {"key": "target_require_lower_general_score", "type": FIELD_BOOL, "label": "Ciclo especial — exigir pontos de generais menor que os meus", "required": False, "default": False},
            {"key": "target_max_score_gap", "type": FIELD_INT, "label": "Ciclo especial — diferença máxima de posição no ranking", "required": False, "default": 5,
             "min": 1, "help": "Quantas posições acima/abaixo no ranking pirata o alvo pode estar."},
            {"key": "targeted_convert_mode", "type": FIELD_CHOICE, "label": "Ciclo especial — converter pontos antes do abandono", "required": False, "default": "all",
             "choices": [("never", "Nunca"), ("all", "Converter tudo"), ("percent", "Converter X%")]},
            {"key": "targeted_convert_percent", "type": FIELD_INT, "label": "Ciclo especial — % a converter antes do abandono", "required": False, "default": 100,
             "min": 1, "max": 100},
        ],
    },
    15: {
        "name": "Espionagem",
        "name_en": "Espionage",
        "category": CAT_MILITARY,
        "icon": "bi-binoculars",
        "runner": "spy",
        "requires_game_session": True,
        "recurring": False,  # Missão finita (espia um alvo até concluir); usa reschedule como retry, não loop eterno
        "long_running": False,
        "ready": True,
        "description": "Envia espiões para cidades inimigas para coletar informações. Salva relatórios no hub.",
        "inputs": [
            # city_id and target are pre-filled from worldintel — hidden in form
            {"key": "city_id", "type": FIELD_CITY_SELECT, "multiple": False, "required": True, "label": "Cidade de origem (com Espionagem)"},
            {"key": "target_city_id", "type": FIELD_INT, "required": True, "label": "ID da cidade alvo"},
            {"key": "island_id", "type": FIELD_INT, "required": True, "label": "ID da ilha"},
            {"key": "target_city_name", "type": FIELD_STR, "required": False, "label": "Nome da cidade alvo"},
            {"key": "target_owner", "type": FIELD_STR, "required": False, "label": "Dono"},
            {"key": "target_owner_id", "type": FIELD_STR, "required": False, "label": "ID do dono"},
            # mission_id is built from checkboxes in the form (intel missions only)
            # mission 1 (infiltração) is ALWAYS automatic — not exposed to user
            {"key": "mission_id", "type": FIELD_STR, "required": False, "default": "3,5",
             "label": "Missões de inteligência",
             "help": "IDs separados por vírgula. Infiltração (missão 1) é sempre automática."},
            {"key": "max_detection_risk", "type": FIELD_INT, "required": False, "default": 35,
             "min": 5, "max": 90, "label": "Risco máximo aceito (%)",
             "help": "Agentes calculados automaticamente para ficar abaixo deste risco. Menor risco = mais agentes necessários."},
            {"key": "recall_after", "type": FIELD_BOOL, "required": False, "default": True,
             "label": "Chamar espiões de volta ao terminar"},
            {"key": "save_reports", "type": FIELD_BOOL, "required": False, "default": True,
             "label": "Salvar relatórios no hub"},
            {"key": "delete_after_save", "type": FIELD_BOOL, "required": False, "default": False,
             "label": "Apagar relatórios do jogo após salvar"},
            {"key": "target_city_name", "type": FIELD_STR, "required": False, "label": "Nome da cidade alvo"},
            {"key": "target_owner", "type": FIELD_STR, "required": False, "label": "Dono da cidade alvo"},
            {"key": "target_owner_id", "type": FIELD_STR, "required": False, "label": "ID do dono alvo"},
        ],
    },
    16: {
        "name": "Espionagem Mundial",
        "name_en": "World Espionage",
        "category": CAT_MILITARY,
        "icon": "bi-binoculars-fill",
        "runner": "world_spy",
        "requires_game_session": True,
        "recurring": True,
        "long_running": False,
        "ready": True,
        "description": "Espia automaticamente múltiplas cidades do WorldDump numa região do mapa. Distribui entre as safehouses configuradas e ignora as contas próprias.",
        "inputs": [
            # Safehouses — IDs separados por vírgula (preenchidos pelo formulário)
            {"key": "city_ids", "type": FIELD_STR, "required": True,
             "label": "IDs das cidades de origem",
             "help": "Cidades com Guilda dos Ladrões. Preenchido automaticamente pelo formulário."},
            # Missões
            {"key": "missions", "type": FIELD_STR, "required": False, "default": "3,5",
             "label": "Missões de inteligência (IDs, vírgula)",
             "help": "3=Estoques, 5=Tropas, 6=Guarnição, 26=Pesquisa. Infiltração (1) é automática."},
            # Região
            {"key": "region_x_min", "type": FIELD_INT, "required": False, "default": 0, "min": 0,
             "label": "Região X mínimo"},
            {"key": "region_x_max", "type": FIELD_INT, "required": False, "default": 99, "min": 0,
             "label": "Região X máximo"},
            {"key": "region_y_min", "type": FIELD_INT, "required": False, "default": 0, "min": 0,
             "label": "Região Y mínimo"},
            {"key": "region_y_max", "type": FIELD_INT, "required": False, "default": 99, "min": 0,
             "label": "Região Y máximo"},
            # Filtros
            {"key": "only_inactive", "type": FIELD_BOOL, "required": False, "default": True,
             "label": "Apenas inativos",
             "help": "Modo férias não pode ser espionado (jogo bloqueia). Sugerido manter ativo."},
            {"key": "max_total_score", "type": FIELD_INT, "required": False, "default": 0, "min": 0,
             "label": "Pontuação total máxima do alvo",
             "help": "0 = sem limite. Alvos com pontuação total (construção+pesquisa+exército) acima disso são ignorados."},
            {"key": "max_army_score", "type": FIELD_INT, "required": False, "default": 0, "min": 0,
             "label": "Pontuação de generais máxima do alvo",
             "help": "0 = sem limite. Alvos com pontuação de exército acima disso são ignorados."},
            # Operação
            {"key": "skip_if_valid", "type": FIELD_BOOL, "required": False, "default": True,
             "label": "Pular se já tem intel válida"},
            {"key": "intel_ttl_hours", "type": FIELD_INT, "required": False, "default": 0,
             "min": 0, "label": "Validade da intel (horas)",
             "help": "0 = usa configuração global (spy_report_expiry_hours). Ex: 48 = reespia após 48h."},
            {"key": "max_targets", "type": FIELD_INT, "required": False, "default": 200,
             "min": 1, "max": 200, "label": "Máximo de alvos", "hidden": True},
            {"key": "max_detection_risk", "type": FIELD_INT, "required": False, "default": 35,
             "min": 5, "max": 90, "label": "Risco máximo aceito (%)"},
            {"key": "recall_after", "type": FIELD_BOOL, "required": False, "default": True,
             "label": "Chamar espiões de volta ao terminar"},
            {"key": "save_reports", "type": FIELD_BOOL, "required": False, "default": True,
             "label": "Salvar relatórios no hub"},
            {"key": "delete_after_save", "type": FIELD_BOOL, "required": False, "default": False,
             "label": "Apagar relatórios do jogo após salvar"},
            # ── Alerta de raid via Telegram ──
            {"key": "raid_alert_enabled", "type": FIELD_BOOL, "required": False, "default": False,
             "label": "Alerta de raid via Telegram",
             "help": "Notifica via Telegram quando uma cidade espionada tiver recursos acima do threshold."},
            {"key": "raid_alert_threshold", "type": FIELD_INT, "required": False, "default": 50000,
             "min": 0, "label": "Threshold de recursos para alerta",
             "help": "Total de recursos (soma de todos os tipos) necessário para disparar o alerta."},
            {"key": "raid_source_city_id", "type": FIELD_CITY_SELECT, "required": False,
             "label": "Cidade de origem para o raid",
             "multiple": False,
             "help": "Cidade com tropas para o raid (pré-preenchido no botão Telegram)."},
            {"key": "raid_transporters", "type": FIELD_INT, "required": False, "default": 0,
             "min": 0, "label": "Navios mercantes para raid (0 = todos disponíveis)"},
            {"key": "raid_max_trips", "type": FIELD_INT, "required": False, "default": 5,
             "min": 1, "label": "Máximo de viagens por raid"},
        ],
    },
    1008: {
        "name": "Roubar Cidade",
        "name_en": "Raid City",
        "category": CAT_MILITARY,
        "icon": "bi-lightning-charge-fill",
        "runner": "raid_city",
        "requires_game_session": True,
        "recurring": False,
        "long_running": True,
        "ready": True,
        "description": (
            "Envia um exército para roubar recursos de uma cidade inimiga. "
            "Suporta múltiplas viagens e cálculo automático de força mínima a partir da intel de espionagem."
        ),
        "inputs": [
            {
                "key": "source_city_id",
                "type": FIELD_CITY_SELECT,
                "label": "Cidade de origem",
                "multiple": False,
                "required": True,
                "help": "Cidade onde estão as tropas e navios mercantes.",
            },
            {
                "key": "target_city_id",
                "type": FIELD_INT,
                "label": "ID da cidade alvo",
                "required": True,
            },
            {
                "key": "island_id",
                "type": FIELD_INT,
                "label": "ID da ilha da cidade alvo",
                "required": True,
            },
            {
                "key": "mode",
                "type": FIELD_CHOICE,
                "label": "Modo",
                "required": True,
                "default": "land",
                "choices": [("land", "Terrestre (saqueio)")],
                "help": "Bloqueio naval será implementado futuramente.",
            },
            {
                "key": "units",
                "type": FIELD_STR,
                "label": "Tropas (JSON)",
                "required": False,
                "help": 'Ex: {"303": 5, "305": 6}. Vazio = calculado automaticamente a partir da intel.',
            },
            {
                "key": "transporters",
                "type": FIELD_INT,
                "label": "Navios mercantes",
                "required": False,
                "default": 0,
                "min": 0,
                "help": "0 = usar todos os disponíveis. Cada navio carrega 500 recursos.",
            },
            {
                "key": "multi_trip",
                "type": FIELD_BOOL,
                "label": "Múltiplas viagens",
                "required": False,
                "default": True,
                "help": "Continuar roubando até esgotar recursos ou atingir o limite de viagens.",
            },
            {
                "key": "max_trips",
                "type": FIELD_INT,
                "label": "Máximo de viagens",
                "required": False,
                "default": 10,
                "min": 1,
                "max": 50,
            },
            {
                "key": "min_resources_to_continue",
                "type": FIELD_INT,
                "label": "Recursos mínimos para continuar (por viagem)",
                "required": False,
                "default": 0,
                "min": 0,
                "help": "Para de enviar se o alvo tiver menos recursos que este valor. 0 = sem limite.",
            },
            {
                "key": "enemy_units",
                "type": FIELD_STR,
                "label": "Tropas inimigas (JSON, da intel)",
                "required": False,
                "help": 'Preenchido automaticamente a partir do relatório de espionagem. Ex: {"315": 4, "301": 1}',
            },
            {
                "key": "wall_level",
                "type": FIELD_INT,
                "label": "Nível da muralha",
                "required": False,
                "default": 1,
                "min": 0,
                "max": 20,
            },
            {
                "key": "needs_blockade",
                "type": FIELD_BOOL,
                "label": "Bloqueio naval primeiro (futuro)",
                "required": False,
                "default": False,
                "help": "Reservado para implementação futura de bloqueio naval antes do saque.",
            },
        ],
    },
    9002: {
        "name": "Revolta",
        "name_en": "Revolt",
        "category": CAT_MILITARY,
        "icon": "bi-flag-fill",
        "runner": "revolt",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ready": True,
        "description": "Inicia uma revolta para libertar cidade ocupada ou porto bloqueado por inimigo.",
        "inputs": [
            {
                "key": "city_id",
                "type": FIELD_CITY_SELECT,
                "label": "Cidade",
                "multiple": False,
                "required": True,
                "help": "Selecione a cidade com ocupacao terrestre ou bloqueio naval.",
            },
            {
                "key": "revolt_type",
                "type": FIELD_CHOICE,
                "label": "Tipo de revolta",
                "required": True,
                "default": "troops",
                "choices": [
                    ("troops", "Forcas de ocupacao (tropas)"),
                    ("ships", "Bloqueio do porto (frotas)"),
                ],
                "help": "Escolha se a revolta deve mirar tropas em terra ou a frota que bloqueia o porto.",
            },
        ],
    },
}
