from .constants import CAT_AUTOMATION, CAT_MILITARY, FIELD_BOOL, FIELD_CHOICE, FIELD_CITY_SELECT, FIELD_INT, FIELD_STR


ACTIONS = {
    1005: {
        "name": "Gerenciar Treino Militar",
        "name_en": "Manage military training",
        "category": CAT_MILITARY,
        "icon": "bi-people-fill",
        "runner": "train_units",
        "requires_game_session": True,
        "recurring": True,
        "long_running": False,
        "ready": True,
        "description": "Treina tropas ou navios em uma cidade. Suporta treino único ou manutenção automática de efetivo.",
        "inputs": [
            {"key": "city_id", "type": FIELD_CITY_SELECT, "label": "Cidade", "multiple": False, "required": False},
            {"key": "building_type", "type": FIELD_CHOICE, "label": "Tipo", "required": True,
             "default": "troops", "choices": [("troops", "Tropas (Quartel)"), ("fleet", "Frotas (Estaleiro)")]},
            {"key": "mode", "type": FIELD_CHOICE, "label": "Modo", "required": True,
             "default": "once", "choices": [("once", "Treinar agora"), ("distribute", "Distribuir treino"), ("maintain", "Manter efetivo")]},
            {"key": "maintain_scope", "type": FIELD_CHOICE, "label": "Escopo da manutencao", "required": False,
             "default": "local", "choices": [("local", "Cidade unica"), ("selected_uniform", "Mesmo alvo em cidades selecionadas"), ("selected_custom", "Alvo customizado por cidade")]},
            {"key": "consolidate_city_id", "type": FIELD_CITY_SELECT, "label": "Consolidar em", "multiple": False, "required": False},
            {"key": "position", "type": FIELD_INT, "label": "Posição do edifício", "required": False, "default": 0,
             "help": "Posição do Quartel/Estaleiro no mapa da cidade (0 = detectar automaticamente)."},
            {"key": "recheck_minutes", "type": FIELD_INT, "label": "Verificar a cada (min)", "required": False,
             "default": 120, "min": 30, "help": "Apenas no modo Manter efetivo."},
        ],
    },
    1202: {
        "name": "Mover Forcas",
        "name_en": "Move forces",
        "category": CAT_MILITARY,
        "icon": "bi-geo-alt-fill",
        "runner": "station_units",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ready": True,
        "description": "Move tropas terrestres de uma cidade para guarnecer outra.",
        "inputs": [
            {"key": "scope", "type": FIELD_CHOICE, "label": "Tipo", "required": True,
             "default": "troops", "choices": [("troops", "Tropas"), ("fleet", "Frotas")]},
            {"key": "from_city_id", "type": FIELD_CITY_SELECT, "label": "Cidade de origem", "multiple": False, "required": True},
            {"key": "to_city_id", "type": FIELD_CITY_SELECT, "label": "Cidade de destino", "multiple": False, "required": True},
        ],
    },
    1203: {
        "name": "Melhorar Unidades",
        "name_en": "Upgrade units",
        "category": CAT_AUTOMATION,
        "icon": "bi-arrow-up-square",
        "runner": "upgrade_units",
        "requires_game_session": True,
        "recurring": True,
        "long_running": False,
        "ready": True,
        "description": "Pesquisa melhorias de unidades na Oficina do Inventor automaticamente. Selecione quais unidades evoluir, nivel maximo e reservas de recursos.",
        "inputs": [
            {
                "key": "city_id",
                "type": FIELD_CITY_SELECT,
                "label": "Cidade",
                "multiple": False,
                "required": False,
                "help": "Deixe em branco para processar todas as cidades que possuem Oficina do Inventor.",
            },
        ],
    },
    17: {
        "name": "Pirata Automatico",
        "name_en": "Auto pirate",
        "category": CAT_MILITARY,
        "icon": "bi-flag-fill",
        "runner": "pirate",
        "requires_game_session": True,
        "recurring": True,
        "long_running": True,
        "description": "Executa missoes piratas automaticamente.",
        "inputs": [],
    },
    15: {
        "name": "Investigar",
        "name_en": "Investigate",
        "category": CAT_MILITARY,
        "icon": "bi-binoculars",
        "runner": "investigate",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "description": "Investiga uma cidade inimiga.",
        "inputs": [],
    },
    9002: {
        "name": "Revolta",
        "name_en": "Revolt",
        "category": CAT_MILITARY,
        "icon": "bi-flag-fill",
        "runner": "revolt",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ready": True,
        "description": "Inicia uma revolta para libertar cidade ocupada ou porto bloqueado por inimigo.",
        "inputs": [
            {
                "key": "city_id",
                "type": FIELD_CITY_SELECT,
                "label": "Cidade",
                "multiple": False,
                "required": True,
                "help": "Selecione a cidade com ocupacao terrestre ou bloqueio naval.",
            },
            {
                "key": "revolt_type",
                "type": FIELD_CHOICE,
                "label": "Tipo de revolta",
                "required": True,
                "default": "troops",
                "choices": [
                    ("troops", "Forcas de ocupacao (tropas)"),
                    ("ships", "Bloqueio do porto (frotas)"),
                ],
                "help": "Escolha se a revolta deve mirar tropas em terra ou a frota que bloqueia o porto.",
            },
        ],
    },
}
