from .constants import CAT_MONITORING, FIELD_BOOL, FIELD_CHOICE, FIELD_CITY_SELECT, FIELD_INT, FIELD_STR, TRANSPORT_LOAD_CHOICES


ACTIONS = {
    601: {
        "name": "Monitor de Ilha",
        "name_en": "Island monitor",
        "category": CAT_MONITORING,
        "icon": "bi-geo-fill",
        "runner": "island_monitor",
        "requires_game_session": True,
        "recurring": True,
        "long_running": False,
        "ready": True,
        "description": "Monitora ilhas e alerta no Telegram quando cidades aparecem, somem ou trocam de jogador. Suporta monitorar ilhas próprias, ilhas inimigas por ID, ou toda uma região do mapa.",
        "inputs": [
            {"key": "monitor_mode", "type": FIELD_CHOICE, "label": "Modo de monitoramento", "required": True,
             "choices": [("islands", "Ilhas específicas"), ("region", "Região do mapa")],
             "default": "islands",
             "help": "Ilhas específicas: selecione cidades próprias e/ou IDs. Região: define um retângulo no mapa."},
            {"key": "own_city_ids", "type": FIELD_CITY_SELECT, "label": "Minhas cidades (monitor a ilha delas)", "multiple": True, "required": False,
             "help": "O sistema detecta automaticamente a ilha de cada cidade selecionada."},
            {"key": "extra_island_ids", "type": FIELD_STR, "label": "IDs de ilhas extras (separados por vírgula)", "required": False,
             "help": "IDs numéricos de ilhas inimigas ou neutras que deseja monitorar."},
            {"key": "region_x_min", "type": FIELD_INT, "label": "X mínimo da região", "required": False, "min": 0, "default": 0},
            {"key": "region_y_min", "type": FIELD_INT, "label": "Y mínimo da região", "required": False, "min": 0, "default": 0},
            {"key": "region_x_max", "type": FIELD_INT, "label": "X máximo da região", "required": False, "min": 0, "default": 0},
            {"key": "region_y_max", "type": FIELD_INT, "label": "Y máximo da região", "required": False, "min": 0, "default": 0},
            {"key": "notify_new", "type": FIELD_BOOL, "label": "Alertar nova cidade", "required": False, "default": True},
            {"key": "notify_removed", "type": FIELD_BOOL, "label": "Alertar cidade sumida", "required": False, "default": True},
            {"key": "notify_change", "type": FIELD_BOOL, "label": "Alertar troca de jogador no slot", "required": False, "default": True},
            {"key": "notify_fight", "type": FIELD_BOOL, "label": "Alertar batalha na ilha", "required": False, "default": False},
            {"key": "recheck_minutes", "type": FIELD_INT, "label": "Intervalo de verificação (min)", "required": True, "min": 5, "default": 60},
        ],
    },
    602: {
        "name": "Dump do Mundo",
        "name_en": "World dump",
        "category": CAT_MONITORING,
        "icon": "bi-binoculars-fill",
        "runner": "world_dump",
        "requires_game_session": True,
        "recurring": False,
        "long_running": True,
        "ready": True,
        "description": "Coleta ilhas e cidades em um escopo definido e salva uma base consultavel por player, ilha e alianca.",
        "inputs": [
            {"key": "dump_mode", "type": FIELD_CHOICE, "label": "Escopo do dump", "required": True,
             "choices": [("own_islands", "Ilhas das minhas cidades"), ("region", "Regiao do mapa")],
             "default": "own_islands",
             "help": "Ilhas das minhas cidades usa as cidades selecionadas. Regiao varre um retangulo do mapa e abre cada ilha encontrada."},
            {"key": "own_city_ids", "type": FIELD_CITY_SELECT, "label": "Minhas cidades", "multiple": True, "required": False,
             "help": "Cada cidade selecionada adiciona a ilha correspondente ao dump."},
            {"key": "region_x_min", "type": FIELD_INT, "label": "X minimo", "required": False, "min": 0, "default": 0},
            {"key": "region_y_min", "type": FIELD_INT, "label": "Y minimo", "required": False, "min": 0, "default": 0},
            {"key": "region_x_max", "type": FIELD_INT, "label": "X maximo", "required": False, "min": 0, "default": 0},
            {"key": "region_y_max", "type": FIELD_INT, "label": "Y maximo", "required": False, "min": 0, "default": 0},
            {"key": "include_empty", "type": FIELD_BOOL, "label": "Incluir ilhas vazias", "required": False, "default": False,
             "help": "Quando desligado, ignora ilhas sem cidade durante a descoberta da regiao."},
        ],
    },
    30: {
        "name": "Verificar Diplomacia",
        "name_en": "Check Diplomacy",
        "category": CAT_MONITORING,
        "icon": "bi-envelope",
        "runner": "diplomacy_check",
        "requires_game_session": True,
        "recurring": True,
        "long_running": False,
        "ready": True,
        "description": "Verifica inbox de diplomacia e envia novas mensagens para o Telegram. Permite responder e tratar pedidos de tratado direto pelo chat.",
        "inputs": [
            {"key": "city_id", "type": FIELD_CITY_SELECT, "label": "Cidade", "multiple": False, "required": True, "help": "Qualquer cidade do jogador (necessário para abrir o advisor de diplomacia)."},
            {"key": "interval_minutes", "type": FIELD_INT, "label": "Intervalo de checagem (min)", "required": True, "min": 5, "default": 60, "help": "Frequência com que o inbox é verificado."},
            {"key": "notify_telegram", "type": FIELD_BOOL, "label": "Notificar no Telegram", "required": False, "default": True, "help": "Envia novas mensagens para o Telegram."},
        ],
    },
    31: {
        "name": "Enviar Mensagem",
        "name_en": "Send Message",
        "category": CAT_MONITORING,
        "icon": "bi-send",
        "runner": "diplomacy_send",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "ready": True,
        "description": "Envia uma mensagem de diplomacia para outro jogador.",
        "inputs": [
            # receiver_name: display only — shown in UI, ignored by runner
            {"key": "receiver_name", "type": FIELD_STR, "label": "Para (jogador)", "required": False, "default": ""},
            # receiver_id: required by runner, rendered as hidden in custom form block
            {"key": "receiver_id", "type": FIELD_INT, "label": "ID do jogador", "required": True},
            # city_id: needed by runner to get session/actionRequest
            {"key": "city_id", "type": FIELD_CITY_SELECT, "label": "Sua cidade", "multiple": False, "required": True,
             "help": "Cidade usada para abrir a sessão de jogo."},
            # msg_type: string — valid values are dynamic (50, 60, 77, 89, 100, 110, 115, 66c*)
            {"key": "msg_type", "type": FIELD_STR, "label": "Tipo", "required": True, "default": "50"},
            # content: main textarea
            {"key": "content", "type": FIELD_STR, "label": "Mensagem", "required": True,
             "textarea": True, "rows": 5, "default": ""},
        ],
    },

    701: {
        "name": "Alerta de Ataques",
        "name_en": "Attack alerts",
        "category": CAT_MONITORING,
        "icon": "bi-exclamation-triangle",
        "runner": "alert_attacks",
        "requires_game_session": True,
        "recurring": True,
        "long_running": True,
        "ready": True,
        "description": "Monitora ataques e envia alertas.",
        "inputs": [
            {"key": "interval_minutes", "type": FIELD_INT, "label": "Intervalo de checagem (min)", "required": True, "min": 3, "default": 20, "help": "Frequencia com que o advisor militar e relido."},
            {"key": "min_troops", "type": FIELD_INT, "label": "Ignorar abaixo de tropas", "required": True, "min": 0, "default": 0, "help": "Ataques com menos tropas do que isso nao geram alerta novo."},
            {"key": "min_fleet", "type": FIELD_INT, "label": "Ignorar abaixo de frotas", "required": True, "min": 0, "default": 0, "help": "Ataques com menos navios do que isso nao geram alerta novo."},
            {"key": "notify_telegram", "type": FIELD_BOOL, "label": "Notificar no Telegram", "required": False, "default": True, "help": "Envia notificacao para ataques novos detectados."},
        ],
    },
    702: {
        "name": "Alerta de Vinho",
        "name_en": "Low wine alerts",
        "category": CAT_MONITORING,
        "icon": "bi-cup-fill",
        "runner": "alert_wine",
        "requires_game_session": True,
        "recurring": True,
        "long_running": True,
        "ready": True,
        "description": "Faz gestao completa de vinho: felicidade total, taverna e envios logísticos sem microajustes.",
        "inputs": [
            {"key": "protect_hours", "type": FIELD_INT, "label": "Nunca deixar abaixo de (h)", "required": True, "min": 1, "default": 24, "help": "Quando uma cidade cair abaixo disso, o sistema age."},
            {"key": "cover_hours", "type": FIELD_INT, "label": "Cobrir ate (h)", "required": True, "min": 1, "default": 168, "help": "Cada envio tenta cobrir esta janela de vinho."},
            {"key": "donor_reserve_hours", "type": FIELD_INT, "label": "Reserva do doador (h)", "required": True, "min": 1, "default": 168, "help": "O doador precisa manter esta folga minima para si."},
            {"key": "useful_transfer_min", "type": FIELD_INT, "label": "Envio minimo util", "required": True, "min": 1, "default": 5000, "help": "Evita transportes pequenos demais, exceto em risco extremo."},
            {"key": "shipment_cap", "type": FIELD_INT, "label": "Envio maximo por remessa", "required": True, "min": 1, "default": 25000, "help": "Limita o tamanho de cada envio criado pelo monitor."},
            {"key": "growth_happiness_floor", "type": FIELD_INT, "label": "Felicidade minima em cidade crescendo", "required": True, "min": 0, "default": 96, "help": "Quando a cidade ainda nao esta cheia, a taverna tenta preservar pelo menos esta satisfacao total."},
            {"key": "transport_load_percent", "type": FIELD_CHOICE, "label": "Carga por barco", "required": True, "choices": TRANSPORT_LOAD_CHOICES, "default": "100", "help": "Usa a mesma estrategia do envio de recursos."},
        ],
    },
    13: {
        "name": "Movimentos de Navios",
        "name_en": "Ship movements",
        "category": CAT_MONITORING,
        "icon": "bi-water",
        "runner": "ship_movements",
        "requires_game_session": True,
        "recurring": False,
        "long_running": False,
        "description": "Monitora movimentos de navios.",
        "inputs": [],
    },
}
